function generatePuebloName() {
  const prefix = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Villa",
    "Mira",
    "El ",
    "La ",
    "Torre",
    "Sierra ",
    "Real ",
    "San ",
    "Santa ",
    "Cumbre ",
    "Monte ",
    "Bella",
    "Nuevo ",
    "Viejo ",
    "Gran ",
    "Calores ",
    "Nueva ",
    "Pueblo ",
    "Poblao ",
    "Isla ",
    "Cerro ",
    "Valle ",
    "Sube ",
    "Baja ",
    "Bosquecillo ",
    "Colina ",
    "Miel",
    "Aguas ",
    "La villa de ",
    "Don ",
    "Doña ",
  ];
  const nouns = [
    "",
    "",
    "",
    "Turbio",
    "Conejos",
    "Floripondios ",
    "Brisilla",
    "Camellos",
    "Valles",
    "Torrijas",
    "Pan",
    "Pepino",
    "Pijo",
    "Pollos",
    "Cebolla",
    "Cellajo",
    "Churro",
    "Almóndiga",
    "Chirimoya",
    "Patatas",
    "Churro",
    "Cacahuete",
    "chamusquina",
    "Pachanga",
    "Zampabollos",
    "Gorgorito",
    "Tiquismiquis",
    "Chuches",
    "Cocretas",
    "Pechuga",
    "Cayetano",
    "Madalenas",
    "Murciegalo",
    "Aguacate",
    "Zapato",
    "Zoquete",
    "Pimpollo",
    "Pezones",
    "Mollete",
    "Palomino",
    "Patones",
    "Brazones",
    "Talones",
    "Secta",
    "Saborío",
    "Sobaco",
    "Cañas",
    "Lechuga",
    "Alcachofa",
    "Chulo",
    "Tuba",
    "Gatos",
    "Mazapanes",
    "Polvorón",
  ];
  const suffix = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    " de la reina",
    " de arriba",
    " de abajo",
    " de al lado",
    " del monte",
    " Montañoso",
    " del rey",
    " del valle",
    " de la Fuente",
    " de la charca",
    " de los calores",
    " del Sur",
    " del Norte",
    " del Este",
    " del Oeste",
    " de las cumbres",
    " de los pinos",
    " de la tobaya",
    " del cateto",
    " del abujero",
    " de la Cuestecilla",
    " de la Torre",
    " del pie",
    " de la pierna",
    " de la barriga",
    " de la roca",
    " de la nalga",
    " Salsero",
    " Tropical",
    " del Sofoco",
    " Abrasador",
    " de la siesta",
    " del los bollos",
    " de la amargura",
    " del no cabo",
    " del campillo",
  ];
  let randomPrefix, randomNoun, randomSuffix;

  do {
    randomPrefix = prefix[Math.floor(Math.random() * prefix.length)];
    randomNoun = nouns[Math.floor(Math.random() * nouns.length)];
    randomSuffix = suffix[Math.floor(Math.random() * suffix.length)];
  } while (randomPrefix === "" && randomNoun === "" && randomSuffix === "");

  return `${randomPrefix}${randomNoun}${randomSuffix}`;
}

window.addEventListener("DOMContentLoaded", (event) => {
  const button = document.getElementById("generate");
  button.addEventListener("click", () => {
    const response = document.getElementById("response");
    const responseText = generatePuebloName();
    response.innerText = responseText;
  });
});
